name: Build APK (diagnostic)

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Prevent long stuck jobs; adjust as needed
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Early debug — show runner info, date, and PATH
        run: |
          echo "=== START DEBUG DUMP ==="
          echo "Date: $(date -u)"
          echo "Runner OS: $RUNNER_OS"
          echo "Runner Temp: $RUNNER_TEMP"
          echo "Workspace: $GITHUB_WORKSPACE"
          echo "Actor: $GITHUB_ACTOR"
          echo "Event name: $GITHUB_EVENT_NAME"
          echo "Repo: $GITHUB_REPOSITORY"
          echo "Branch (git): $(git rev-parse --abbrev-ref HEAD || echo 'no-git')"
          echo "-------------------------"
          echo "PATH:"
          echo "$PATH"
          echo "-------------------------"
          echo "Environment variables (filtered):"
          env | sed -n '1,200p'
          echo "=== END DEBUG DUMP ==="

      - name: List repo root + workflow file content
        run: |
          echo "PWD: $(pwd)"
          echo "Listing repo root:"
          ls -la
          echo "Listing .github/workflows:"
          ls -la .github/workflows || true
          echo "Show the workflow file:"
          echo "---- BEGIN WORKFLOW ----"
          sed -n '1,200p' .github/workflows/android-build.yml || true
          echo "---- END WORKFLOW ----"

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Ensure gradle wrapper is executable
        run: |
          if [ -f ./gradlew ]; then chmod +x ./gradlew; fi
          echo "gradlew exists? $(test -f ./gradlew && echo yes || echo no)"

      - name: Print java and gradle versions
        run: |
          java -version || true
          if [ -f ./gradlew ]; then ./gradlew --version || true; fi

      - name: Quick fail-safe step to confirm logs appear
        run: |
          echo "This step finishes successfully. If you see this in logs, the workflow is running."
